spring:
  application:
    # This should match the name used in config files
    name: davidfperezm-rodriguezlukas-uscateguial
  config:
    # Config server url
    import: configserver:http://localhost:8888
    